name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
         python -m venv .venv
         .venv/bin/pip install --upgrade pip wheel setuptools
         .venv/bin/pip install pre-commit pytest flake8 black isort
      - name: Install pre-commit hooks
        run: .venv/bin/pre-commit install

      - name: Run linters and format checks
        run: .venv/bin/pre-commit run --all-files

      - name: Run tests
        run: .venv/bin/pytest --disable-warnings -q

