name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Lint with flake8
        run: |
          flake8 custom_components

      - name: Check formatting with black
        run: |
          black --check custom_components

      - name: Type check with mypy
        run: |
          mypy custom_components

      - name: Run tests
        run: |
          pytest --cov=custom_components/deye_inverter --cov-report=term-missing
